Repository findthemasks/findthemasks, pull requests merged in 2020-04, with the labels that each got.

#396 Render the list 40 entries at a time with infinite scroll.
  public/index.html
  public/locations-list-map.js
Labels: enhancement, high-priority

#407 Feature/google analytics user interactions
  public/locations-list-map.js
Labels: analytics

#397 add Portugal, Poland, Spain, Switzerland, UK, Austria, Italy, Germany
  public/at
  public/countries.js
  public/donation-form-bounce.html
  public/es
  public/i18n/ar-ma.json
  public/i18n/de-de.json
  public/i18n/en.json
  public/i18n/es-es.json
  public/i18n/fr-fr.json
  public/i18n/it-it.json
  public/i18n/ja-jp.json
  public/i18n/ko-kr.json
  public/i18n/pl-pl.json
  public/i18n/pt-pt.json
  public/i18n/qqq.json
  public/i18n/zh-tw.json
  public/it
  public/locations-list-map.js
  public/pl
  public/pt
Labels: high-priority

#548 Indent content to separate entries from each other
  public/style.css
Labels: ui/ux

#578 Feature/analytics for social buttons
  public/i18n/en.json
  public/locations-list-map.js
  public/style.css
  views/partials/bottom_nav.handlebars
Labels: analytics

#643 add query string versioning where possible to mitigate caching issue
  server.js
  views/layouts/give.handlebars
  views/layouts/main.handlebars
  views/layouts/static.handlebars
  views/partials/top_nav.handlebars
  views/stats.handlebars
Labels: do not merge

#695 fix entry.orgType back to entry.org_type
  client/locations-list-map.js
Labels: bug

#715 Finishes #709 add redirect from gb -> uk and make uk the canonical code
  client/countries.js
  client/locations-list-map.js
  functions/index.js
  public/images/icons.data.svg.css
  server.js
Labels: do not merge

#718 Feature/faq page ux2
  client/faq.js
  public/i18n/ar-ma.json
  public/i18n/de-de.json
  public/i18n/en.json
  public/i18n/es-es.json
  public/i18n/fr-fr.json
  public/i18n/hi-in.json
  public/i18n/it-it.json
  public/i18n/ja-jp.json
  public/i18n/ko-kr.json
  public/i18n/nl-nl.json
  public/i18n/pl-pl.json
  public/i18n/pt-pt.json
  public/i18n/ru-ru.json
  public/i18n/zh-tw.json
  public/images/icons/dash.svg
  public/images/icons/plus.svg
  sass/style.css
  views/faq.handlebars
  views/partials/countries/ca/large_donation_sites.handlebars
  views/partials/countries/ca/mask_match.handlebars
  views/partials/countries/default/large_donation_sites.handlebars
  views/partials/countries/us/mask_match.handlebars
  webpack.config.js
Labels: ui/ux

#727 enable email relay for users who have not opted out
  .gitignore
  client/locations-list-map.js
  functions/index.js
Labels: do not merge

#735 Feature/volunteer page ux2
  client/locations-list-map.js
  public/images/fb.svg
  public/images/icons/addlroles.svg
  public/images/icons/i18n.svg
  sass/give.scss
  sass/icons.data.svg.scss
  sass/style.scss
  views/faq.handlebars
  views/layouts/give.handlebars
  views/layouts/main.handlebars
  views/layouts/static.handlebars
  views/partners.handlebars
  views/volunteer.handlebars
  views/whoweare.handlebars
  webpack.config.js
Labels: do not merge

#729 Findthemakers embed and other fixes
  client/countries.js
  client/getCountry.js
  client/locations-list-map.js
  middleware/setCurrentCountry.js
  package-lock.json
  package.json
  public/data-makers.json
  public/makers-us.json
  public/makers.json
  sass/give.scss
  server.js
  views/give.handlebars
  views/index.handlebars
  views/layouts/give.handlebars
  views/layouts/main.handlebars
  views/layouts/static.handlebars
  views/makers.handlebars
  views/partials/js-setup.handlebars
Labels: makers
