Repository findthemasks/findthemasks, pull requests merged in 2020-05, with the labels that each got.

#922 add hover/highlighted style to give scss
  sass/give.scss
Labels: bug

#925 Adds bones of datablog 2.
  applicationRoutes.js
  public/i18n/en.json
  public/images/needs20200514.png
  public/images/needs20200514Preview.png
  public/images/shortages20200514.png
  views/blog/2020_05_14_data_update.handlebars
  views/layouts/static.handlebars
Labels: do not merge

#946 Feature/makerspace faq changes
  public/i18n/ar-ma.json
  public/i18n/de-de.json
  public/i18n/en.json
  public/i18n/es-es.json
  public/i18n/fr-fr.json
  public/i18n/hi-in.json
  public/i18n/it-it.json
  public/i18n/ja-jp.json
  public/i18n/ko-kr.json
  public/i18n/nl-nl.json
  public/i18n/pl-pl.json
  public/i18n/pt-pt.json
  public/i18n/ru-ru.json
  public/i18n/zh-tw.json
  views/faq.handlebars
  views/partials/makers_faq.handlebars
Labels: makers

#880 Add OSMS data into makers dataset.
  client/locations-list-map.js
  functions/airtable-connector.js
  functions/airtable-shared-view.js
  functions/geocode.js
  functions/index.js
  functions/package-lock.json
  functions/package.json
  public/i18n/ar-ma.json
  public/i18n/de-de.json
  public/i18n/en.json
  public/i18n/es-es.json
  public/i18n/fr-fr.json
  public/i18n/hi-in.json
  public/i18n/it-it.json
  public/i18n/ja-jp.json
  public/i18n/ko-kr.json
  public/i18n/nl-nl.json
  public/i18n/pl-pl.json
  public/i18n/pt-pt.json
  public/i18n/ru-ru.json
  public/i18n/zh-tw.json
Labels: makers
